# SPDX-License-Identifier: MIT-0
---
- name: Download clickhouse-common-static
  ansible.builtin.get_url:
    url: "{{ clickhouse_deb_base_url }}/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_{{ clickhouse_deb_arch }}.deb"
    dest: "{{ clickhouse_tmp_dir }}/clickhouse-common-static_{{ clickhouse_version }}_{{ clickhouse_deb_arch }}.deb"
    mode: "0644"

- name: Download clickhouse-client and clickhouse-server
  ansible.builtin.get_url:
    url: "{{ clickhouse_deb_base_url }}/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
    dest: "{{ clickhouse_tmp_dir }}/{{ item }}_{{ clickhouse_version }}_all.deb"
    mode: "0644"
  loop:
    - clickhouse-client
    - clickhouse-server

- name: Install clickhouse-common-static
  ansible.builtin.apt:
    deb: "{{ clickhouse_tmp_dir }}/clickhouse-common-static_{{ clickhouse_version }}_{{ clickhouse_deb_arch }}.deb"
    state: present
  notify: Start clickhouse service

- name: Install clickhouse-client and clickhouse-server
  ansible.builtin.apt:
    deb: "{{ clickhouse_tmp_dir }}/{{ item }}_{{ clickhouse_version }}_all.deb"
    state: present
  loop:
    - clickhouse-client
    - clickhouse-server
  notify: Start clickhouse service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database {{ clickhouse_database }};'"
  register: clickhouse_create_db
  failed_when: clickhouse_create_db.rc != 0 and clickhouse_create_db.rc != 82
  changed_when: clickhouse_create_db.rc == 0

# tasks file for clickhouse
